### ISSUE TITLE
rich

### ISSUE THREAD

**Issue by FlixyOnBoard** [MalwareMakers/HarBringer-V2#1]
C:\Users\***\OneDrive\Desktop\HarBringer-V2-main>py C:\Users\***\OneDrive\Desktop\HarBringer-V2-main\builder.py
Traceback (most recent call last):
  File "C:\Users\***\OneDrive\Desktop\HarBringer-V2-main\builder.py", line 3, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

obv rich is also installed to the last version

**Comment by MalwareMakers** [comment]
Try installing rich separately rather than using my installer. If you have, check your scripts path, I had the same issue where PowerShell/cmd wouldn't recognise paths so you have to manually add them.

**Comment by MalwareMakers** [comment]
Have you installed both the Microsoft python and the official python by any chance?

**Comment by FlixyOnBoard** [comment]
yes

**Comment by MalwareMakers** [comment]
Ok so the problem with this is that Microsoft is really dumb about managing packages, uninstall your offical python orm tthe python website, disable the python from the micorfost store,

**Comment by FlixyOnBoard** [comment]
just downloaded python 3.10 and worked fine, lmao i guess
