### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by 370k** [MalwareMakers/HarBringer-V2#2]
the bot will work even if it's offline (it'll be everytime off)
the installer is not required
if you got problems with module named rich you can find some fix in the internet, i just downloaded python 3.10 and worked fine
the commands you type in the bot channel have a 2 seconds delay for answering

why am i doin this, cuz i'm dumb af and asked malware :)

**Comment by MalwareMakers** [comment]
As a response to this:
a) its designed to work like this, as in working every time unless you revoke your bot token or you delete your server token. Its designed to run every time a person turns on their computer.  
b) The installer may not be required but you can't send the final payload to anyone easily. The file size is to big. The installer allows you to send a small file which can install the final medium. 
c) The delay comes from the internet connection speed and processing time of the program itself.
